name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create static build
        run: |
          echo "Creating static build..."
          npm run build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_RESUMEBUILDER_BF672 }}'
          channelId: live
          projectId: resumebuilder-bf672
